### ISSUE TITLE
'dictionary changed size during iteration' error in log_result

### ISSUE THREAD

**Issue by slomkowski** [jamesoff/simplemonitor#623] opened 2020-09-15 23:13 UTC
I frequently see following exception in logs:

```
2020-09-15 23:30:11    ERROR (simplemonitor) Caught unhandled exception during main loop
Traceback (most recent call last):
  File "/root/monitor/simplemonitor/simplemonitor/simplemonitor.py", line 766, in run
    self.run_loop()
  File "/root/monitor/simplemonitor/simplemonitor/simplemonitor.py", line 735, in run_loop
    self.do_alerts()
  File "/root/monitor/simplemonitor/simplemonitor/simplemonitor.py", line 663, in do_alerts
    self.do_alert(alerter)
  File "/root/monitor/simplemonitor/simplemonitor/simplemonitor.py", line 583, in do_alert
    for (name, monitor) in host_monitors.items():
RuntimeError: dictionary changed size during iteration
```
also

```
2020-09-16 00:52:54    ERROR (simplemonitor) exception while logging remote monitors
Traceback (most recent call last):
  File "/root/monitor/simplemonitor/simplemonitor/simplemonitor.py", line 547, in log_result
    for (name, monitor) in host_monitors.items():
RuntimeError: dictionary changed size during iteration
```

I haven't yet investigated issue in depth, just leaving stack traces here.

**Comment by jamesoff** [comment] 2020-09-16 08:42
I have an idea what's happening there; I recently "optimized" those loops but may have overdone it :)

**Comment by jamesoff** [comment] 2020-09-17 20:40
Do you have remote instances sending to this one? I think that's the only way the `remote_monitors` dict would change while those loops (in the exceptions) were running.

**Comment by slomkowski** [comment] 2020-09-17 22:08
Yes, I have several machines sending to this one.

**Comment by jamesoff** [comment] 2020-09-18 08:00
Thanks, that explains why the bug is happening, now I just need to fix it :)

**Comment by jamesoff** [comment] 2020-09-19 11:16
@slomkowski Was able to reproduce the error and have hopefully addressed it. Are you able to test the `bugfix/network-thread` branch to see if it resolves the issue for you? You only need it on the instance which is receiving the network data, not all the remote instances sending it.

**Comment by slomkowski** [comment] 2020-09-19 17:10
@jamesoff I deployed the change to my machine. I'll inform if any exception occurs in following 24 h.

**Comment by slomkowski** [comment] 2020-09-20 21:48
There was no exception since I introduced the change, however I see another problem. I have 4 remote machines reporting to this instance, but on the status page I see only 3 of them.  I think it happened before your change too.

When one is visible, the other is not. Both of them are behind NAT, so they have the same IP visible by main instance.

**Comment by slomkowski** [comment] 2020-09-21 10:03
I looked at the code and it seems that remote IP address is used as the key of the map in `self.remote_monitors` in `SimpleMonitor` class. I think it should be changed to some other key which is unique to machine or instance.

Ideas:
* IP + hostname
* hashed remote machine MAC address
* static key typed by hand in configuration

What is your opinion @jamesoff? These changes probably require remote protocol change.

**Comment by jamesoff** [comment] 2020-09-21 12:53
Yeah, I was thinking it was because the host or IP of the incoming connection was used as the key for the dict, but hadn't had a chance to check. Thanks for looking :)

I also agree that the user should be able to specify some kind of machine/instance ID in this case. Since monitors already use the machine's self-identified hostname for their `running_on` property, I'd probably use this as the default for the dict key for `remote_monitors`, with a config option to allow the user to override it (i.e. basically your first suggestion). Monitors would continue to use the value they obtain now for `running_on`.

It will definitely require a change to the protocol for the JSON data sent by remote instances, but this is something I'd been thinking about anyway because I have other uses for a receiving instance to have more metadata about the sender. It would be fairly straightforward to support both formats, and (like the old pickle stuff) the code can be removed after a while too.

**Comment by slomkowski** [comment] 2020-09-22 13:02
@jamesoff are you going to implement it by yourself or should I help you with that?

**Comment by jamesoff** [comment] 2020-09-24 09:04
I'm happy to do it, I should have some time this weekend to look at it.

**Comment by jamesoff** [comment] 2020-09-27 20:08
Initial work on the `feature/protocol` branch if you'd like to try it. Add `client_name=something` to the network logger configuration.

**Comment by slomkowski** [comment] 2020-09-28 16:39
I pulled this branch on my main machine and one of the machines behind NAT The other machine behind NAT uses an old version.

For now, looks OK to me, reports from both machines are visible. Thank you!

**Comment by jamesoff** [comment] 2020-10-11 09:13
Merged to develop

**Closed by jamesoff** 2020-10-11 09:13 UTC
Labels: bug
