### ISSUE TITLE
ping times not displayed

### ISSUE THREAD

**Issue by pteek** [jamesoff/simplemonitor#78] opened 2018-03-29 11:33 UTC
I am testing on win7 with python 3.6.

last_run_duration is logged but the actual ping time is not. I looked into this and may have found something.

in  simplemonitor/Monitors/network.py

within MonitorHost class, run_test function is present

```
    def run_test(self):
        r = re.compile(self.ping_regexp)
        r2 = re.compile(self.time_regexp)
        success = False
        pingtime = 0.0
        try:
            cmd = (self.ping_command % self.host).split(' ')
            output = subprocess.check_output(cmd)
            for line in str(output).split("\n"):
                matches = r.search(line)
                if matches:
                    success = True
                else:
                    matches = r2.search(line)
                    if matches:
                        pingtime = matches.group("ms")
        except Exception as e:
            self.record_fail(e)
            return False
        if success:
            if pingtime > 0:
                self.record_success("%sms" % pingtime)
            else:
                self.record_success()
            return True
        self.record_fail()
return False
```

~~If the first regex (r) is matched, the next one is not run. The next regex is the one that grabs the actual ping time and stores it in last_result via self.record_success.~~
Edit: As it happens, I overlooked the for loop. ~~Still looking.~~
Edit: Problem is with:

`for line in str(output).split("\n"): `

output needs to be decoded like this:

`for line in output.decode('utf-8').split("\n"):`

ultimately, i'd like the actual ping to be logged. If the above is fixed, is the only way to print that is by modifying save_result2 in FileLogger? Or is there an option that I overlooked?

PS: How do I quote code here without literally pasting it?

**Comment by jamesoff** [comment] 2018-03-30 14:47
This is with a recent master? That's entirely possible, I fixed a bunch of places where that decode() call needed to be in there but I guess that one probably got overlooked.

Let me take a look at getting your fix in and also about logging the times; it's possible that's not supported without some code changes, I don't recall :)

**Comment by jamesoff** [comment] 2018-04-05 21:00
@pteek Have a look at this branch? https://github.com/jamesoff/simplemonitor/tree/feature/ping-logging

I couldn't reproduce your error of the output needing decoding, although I've applied the fixes to subprocess output to it I used elsewhere in the Python 3 conversion.

The host monitor was already recording the ping time on success, but the logfile logger wasn't making use of the info for the `ok` lines; I've fixed that.

**Comment by pteek** [comment] 2018-04-06 11:48
Those are similar to the changes I made. I was in a hurry then and just used the changes and didn't push. Didn't even setup a repo.

This is exactly what is needed. Thanks.

How about each monitor being able to log in different loggers based on config? Or each logger being able to write to different destination(files, server, ports etc.)  based on the monitor's name or config?

i.e. a way to separate (files in my case, where it is needed the most) logs for easy comprehension without full fledged monitoring or aggregation system.

**Comment by jamesoff** [comment] 2018-04-06 12:56
There's code which almost does this which got merged recently (it was bundled into the python3 stuff), and lets you specify groups for monitors and alerters, but not loggers. I'll look at getting it added to loggers too.

**Comment by jamesoff** [comment] 2018-04-06 12:56
Oh, is that to say that you've tested the code and it's good for you? I'll merge it if so :)

**Comment by pteek** [comment] 2018-04-06 13:15
Great!

I have tested my duct tape code. If that's holding, then this seems like it'd do just fine.

Still, I'll test this and let you know :)

Also, another thing, the time in "failed since" is printed in UTC .

**Comment by jamesoff** [comment] 2018-04-06 13:31
That one I'm aware of: #53 

And I've not given it any more thought yet beyond that issue yet I'm afraid

Although now SimpleMonitor supports Python 3 maybe it can be fixed, at least for py3...

**Comment by jamesoff** [comment] 2018-07-13 17:30
Closing this issue as the problem it's for seems resolved.

**Closed by jamesoff** 2018-07-13 17:30 UTC
Labels: bug
